/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameAjuda.java
 *
 * Created on 10/07/2011, 01:34:31
 */
package dbd4topostgres;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author frank
 */
public class FrameAjuda extends javax.swing.JFrame {
    BufferedImage iconeSistema = null;
    /** Creates new form FrameAjuda */
    public FrameAjuda() {
        initComponents();
        try {            
            this.iconeSistema = ImageIO.read(this.getClass().getClassLoader().getResourceAsStream("dbd4topostgres/resources/x_centopeia_icone.png"));
        } catch (IOException e) {
        }
        this.setIconImage(this.iconeSistema);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAjuda = new javax.swing.JPanel();
        panelNorth = new javax.swing.JPanel();
        lblIconeXCentopeia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPaneTextoAjuda = new javax.swing.JEditorPane();
        panelCenter = new javax.swing.JPanel();
        scrollPaneImagemDataTypes = new javax.swing.JScrollPane();
        lblImagemDataTypes = new javax.swing.JLabel();
        panelSouth = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dbd4topostgres.Dbd4topostgresApp.class).getContext().getResourceMap(FrameAjuda.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Form"); // NOI18N
        setUndecorated(true);

        panelAjuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelAjuda.setName("panelAjuda"); // NOI18N
        panelAjuda.setPreferredSize(new java.awt.Dimension(720, 500));
        panelAjuda.setLayout(new java.awt.BorderLayout());

        panelNorth.setName("panelNorth"); // NOI18N
        panelNorth.setLayout(new java.awt.BorderLayout());

        lblIconeXCentopeia.setBackground(resourceMap.getColor("lblIconeXCentopeia.background")); // NOI18N
        lblIconeXCentopeia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeXCentopeia.setIcon(resourceMap.getIcon("lblIconeXCentopeia.icon")); // NOI18N
        lblIconeXCentopeia.setToolTipText(resourceMap.getString("lblIconeXCentopeia.toolTipText")); // NOI18N
        lblIconeXCentopeia.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblIconeXCentopeia.setMaximumSize(lblIconeXCentopeia.getPreferredSize());
        lblIconeXCentopeia.setMinimumSize(lblIconeXCentopeia.getPreferredSize());
        lblIconeXCentopeia.setName("lblIconeXCentopeia"); // NOI18N
        lblIconeXCentopeia.setOpaque(true);
        lblIconeXCentopeia.setPreferredSize(new java.awt.Dimension(100, 100));
        lblIconeXCentopeia.setRequestFocusEnabled(false);
        panelNorth.add(lblIconeXCentopeia, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        editorPaneTextoAjuda.setContentType(resourceMap.getString("editorPaneTextoAjuda.contentType")); // NOI18N
        editorPaneTextoAjuda.setEditable(false);
        editorPaneTextoAjuda.setText(resourceMap.getString("editorPaneTextoAjuda.text")); // NOI18N
        editorPaneTextoAjuda.setName("editorPaneTextoAjuda"); // NOI18N
        jScrollPane1.setViewportView(editorPaneTextoAjuda);

        panelNorth.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelAjuda.add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setName("panelCenter"); // NOI18N
        panelCenter.setPreferredSize(new java.awt.Dimension(750, 400));
        panelCenter.setLayout(new java.awt.BorderLayout());

        scrollPaneImagemDataTypes.setBackground(resourceMap.getColor("scrollPaneImagemDataTypes.background")); // NOI18N
        scrollPaneImagemDataTypes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneImagemDataTypes.setAutoscrolls(true);
        scrollPaneImagemDataTypes.setName("scrollPaneImagemDataTypes"); // NOI18N

        lblImagemDataTypes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImagemDataTypes.setIcon(resourceMap.getIcon("lblImagemDataTypes.icon")); // NOI18N
        lblImagemDataTypes.setToolTipText(resourceMap.getString("lblImagemDataTypes.toolTipText")); // NOI18N
        lblImagemDataTypes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblImagemDataTypes.setAlignmentY(0.0F);
        lblImagemDataTypes.setAutoscrolls(true);
        lblImagemDataTypes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        lblImagemDataTypes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagemDataTypes.setIconTextGap(0);
        lblImagemDataTypes.setName("lblImagemDataTypes"); // NOI18N
        lblImagemDataTypes.setOpaque(true);
        lblImagemDataTypes.setPreferredSize(new java.awt.Dimension(600, 720));
        lblImagemDataTypes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        scrollPaneImagemDataTypes.setViewportView(lblImagemDataTypes);

        panelCenter.add(scrollPaneImagemDataTypes, java.awt.BorderLayout.CENTER);

        panelAjuda.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setName("panelSouth"); // NOI18N
        panelSouth.setPreferredSize(new java.awt.Dimension(500, 40));
        panelSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(dbd4topostgres.Dbd4topostgresApp.class).getContext().getActionMap(FrameAjuda.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setBackground(resourceMap.getColor("closeButton.background")); // NOI18N
        closeButton.setFont(resourceMap.getFont("closeButton.font")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeButton.setName("closeButton"); // NOI18N
        closeButton.setOpaque(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        panelSouth.add(closeButton);

        panelAjuda.add(panelSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelAjuda, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameAjuda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane editorPaneTextoAjuda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIconeXCentopeia;
    private javax.swing.JLabel lblImagemDataTypes;
    private javax.swing.JPanel panelAjuda;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JScrollPane scrollPaneImagemDataTypes;
    // End of variables declaration//GEN-END:variables
}
