/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameHelp.java
 *
 * Created on 10/07/2011, 01:34:31
 */
package dbd4topostgres;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author frank
 */
public class FrameHelp extends javax.swing.JFrame {

    BufferedImage iconeSistema = null;

    /** Creates new form FrameHelp */
    public FrameHelp() {
        initComponents();
        try {
            this.iconeSistema = ImageIO.read(this.getClass().getClassLoader().getResourceAsStream("dbd4topostgres/resources/x_centopeia_icone.png"));
        } catch (IOException e) {
        }
        this.setIconImage(this.iconeSistema);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHelp = new javax.swing.JPanel();
        panelNorth = new javax.swing.JPanel();
        lblIconeXCentopeia = new javax.swing.JLabel();
        jScrollPaneHelpText = new javax.swing.JScrollPane();
        editorPaneHelpText = new javax.swing.JEditorPane();
        panelCenter = new javax.swing.JPanel();
        scrollPaneDataTypesImage = new javax.swing.JScrollPane();
        lblDataTypesImage = new javax.swing.JLabel();
        panelSouth = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dbd4topostgres.Dbd4topostgresApp.class).getContext().getResourceMap(FrameHelp.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Form"); // NOI18N
        setUndecorated(true);

        panelHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelHelp.setName("panelHelp"); // NOI18N
        panelHelp.setPreferredSize(new java.awt.Dimension(720, 500));
        panelHelp.setLayout(new java.awt.BorderLayout());

        panelNorth.setName("panelNorth"); // NOI18N
        panelNorth.setLayout(new java.awt.BorderLayout());

        lblIconeXCentopeia.setBackground(resourceMap.getColor("lblIconeXCentopeia.background")); // NOI18N
        lblIconeXCentopeia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeXCentopeia.setIcon(resourceMap.getIcon("lblIconeXCentopeia.icon")); // NOI18N
        lblIconeXCentopeia.setToolTipText(resourceMap.getString("lblIconeXCentopeia.toolTipText")); // NOI18N
        lblIconeXCentopeia.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblIconeXCentopeia.setMaximumSize(lblIconeXCentopeia.getPreferredSize());
        lblIconeXCentopeia.setMinimumSize(lblIconeXCentopeia.getPreferredSize());
        lblIconeXCentopeia.setName("lblIconeXCentopeia"); // NOI18N
        lblIconeXCentopeia.setOpaque(true);
        lblIconeXCentopeia.setPreferredSize(new java.awt.Dimension(100, 100));
        lblIconeXCentopeia.setRequestFocusEnabled(false);
        panelNorth.add(lblIconeXCentopeia, java.awt.BorderLayout.LINE_START);

        jScrollPaneHelpText.setName("jScrollPaneHelpText"); // NOI18N

        editorPaneHelpText.setContentType(resourceMap.getString("editorPaneHelpText.contentType")); // NOI18N
        editorPaneHelpText.setEditable(false);
        editorPaneHelpText.setText(resourceMap.getString("editorPaneHelpText.text")); // NOI18N
        editorPaneHelpText.setName("editorPaneHelpText"); // NOI18N
        jScrollPaneHelpText.setViewportView(editorPaneHelpText);

        panelNorth.add(jScrollPaneHelpText, java.awt.BorderLayout.CENTER);

        panelHelp.add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setName("panelCenter"); // NOI18N
        panelCenter.setPreferredSize(new java.awt.Dimension(750, 400));
        panelCenter.setLayout(new java.awt.BorderLayout());

        scrollPaneDataTypesImage.setBackground(resourceMap.getColor("scrollPaneDataTypesImage.background")); // NOI18N
        scrollPaneDataTypesImage.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneDataTypesImage.setAutoscrolls(true);
        scrollPaneDataTypesImage.setName("scrollPaneDataTypesImage"); // NOI18N

        lblDataTypesImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataTypesImage.setIcon(resourceMap.getIcon("lblDataTypesImage.icon")); // NOI18N
        lblDataTypesImage.setToolTipText(resourceMap.getString("lblDataTypesImage.toolTipText")); // NOI18N
        lblDataTypesImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDataTypesImage.setAlignmentY(0.0F);
        lblDataTypesImage.setAutoscrolls(true);
        lblDataTypesImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        lblDataTypesImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDataTypesImage.setIconTextGap(0);
        lblDataTypesImage.setName("lblDataTypesImage"); // NOI18N
        lblDataTypesImage.setOpaque(true);
        lblDataTypesImage.setPreferredSize(new java.awt.Dimension(600, 720));
        lblDataTypesImage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        scrollPaneDataTypesImage.setViewportView(lblDataTypesImage);

        panelCenter.add(scrollPaneDataTypesImage, java.awt.BorderLayout.CENTER);

        panelHelp.add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setName("panelSouth"); // NOI18N
        panelSouth.setPreferredSize(new java.awt.Dimension(500, 40));
        panelSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(dbd4topostgres.Dbd4topostgresApp.class).getContext().getActionMap(FrameHelp.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setBackground(resourceMap.getColor("closeButton.background")); // NOI18N
        closeButton.setFont(resourceMap.getFont("closeButton.font")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeButton.setName("closeButton"); // NOI18N
        closeButton.setOpaque(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        panelSouth.add(closeButton);

        panelHelp.add(panelSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelHelp, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameHelp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane editorPaneHelpText;
    private javax.swing.JScrollPane jScrollPaneHelpText;
    private javax.swing.JLabel lblDataTypesImage;
    private javax.swing.JLabel lblIconeXCentopeia;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelHelp;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JScrollPane scrollPaneDataTypesImage;
    // End of variables declaration//GEN-END:variables
}
